remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide | Decode ServiceNow with Real-World Tips & Automations
description: A modern ServiceNow blog with hands-on guides, dev insights, and no-fluff automation wisdom from a product-minded builder.
url: "https://nowglide.com"
baseurl: ""
email: "simranjazz@gmail.com"
author: "Gursimran Singh Saini"
timezone: "Asia/Kolkata"

markdown: kramdown
future: true

# site-css: assets/css/style.css

avatar: "/assets/images/gsFormal.JPG"

social-network-links:
  email: "simranjazz@gmail.com"
  linkedin: "simranjazz"

share-buttons: true

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true
  reddit: true

url-pretty: "NowGlide.com"

post_search: true

title-on-all-pages: true

keywords: "ServiceNow, Service-Now, NowGlide, GlideFast, GlideSoft, ServiceNow tips, ServiceNow tricks, ServiceNow blog, Learn ServiceNow, ServiceNow developer, ServiceNow admin, ServiceNow automation, ServiceNow HRSD, ServiceNow ITSM, ServiceNow CSM, ServiceNow scripting, GlideRecord examples, ServiceNow flow designer, ServiceNow integration, ServiceNow admin guide, ServiceNow developer guide, ServiceNow studio, how to use ServiceNow, ServiceNow certification, ServiceNow beginners guide, ServiceNow low-code, ServiceNow training free, Now Platform, Flow Designer, What is ServiceNow, ServiceNow REST API, ServiceNow CMDB explained, ServiceNow custom apps, ServiceNow implementation guide, ServiceNow interview questions, ServiceNow best practices"

navbar-links:
  About Me: "/aboutme/"
  Resume: "https://simranjazz.com"
  Tags: "/tags/"

title-img: "/assets/images/NowGlideLogoInverse.png"

feed_show_tags: true

plugins:
  - jekyll-sitemap

post_footer_author: >
  **Written by:** Gursimran Singh Saini – Self-taught ServiceNow explorer,
  Assistant Director @ EY, passionate about modern automations, learning, and sharing.