remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide
description: Learn ServiceNow tips, tricks, and architecture!
url: "https://simranjazz.github.io"
baseurl: "/NowGlide"
email: "simranjazz@gmail.com"
author: "Gursimran Singh Saini"
timezone: "Asia/Kolkata"

# Build settings
markdown: kramdown

site-css: assets/css/style.css

navbar-col: "#80B6A1"

avatar: "/assets/images/gs.png"
round-avatar: false