remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide
description: Learn ServiceNow tips, tricks, and architecture!
url: "https://simranjazz.github.io"
baseurl: "/NowGlide"
email: "simranjazz@gmail.com"
author: "Gursimran Singh Saini"
timezone: "Asia/Kolkata"

# Build settings
markdown: kramdown

site-css: assets/css/style.css

navbar-col: "#80B6A1"

avatar: "/assets/images/gs.png"

social-network-links:
  email: "simranjazz@gmail.com"
  linkedin: "simranjazz"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true
  reddit: true

url-pretty: "NowGlide.com"

post_search: true

title-on-all-pages: true

keywords: "ServiceNow, Service-Now, GlideFast, GlideSoft, ServiceNow Tips, ServiceNow Tricks, ServiceNow Blog"

navbar-links:
  About Me: "aboutme"
  Author's home: "https://simranjazz.com"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"