remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide ServiceNow-verse
description: Glide Through ServiceNow-verse
url: "https://simranjazz.github.io"
baseurl: "/NowGlide"
email: "simranjazz@gmail.com"
author: "Gursimran Singh Saini"
timezone: "Asia/Kolkata"

# Build settings
markdown: kramdown

site-css: assets/css/style.css

# navbar-col: "#80B6A1"

avatar: "/assets/images/gs.png"

social-network-links:
  email: "simranjazz@gmail.com"
  linkedin: "simranjazz"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true
  reddit: true

url-pretty: "NowGlide.com"

post_search: true

title-on-all-pages: true

keywords: "ServiceNow, Service-Now, GlideFast, GlideSoft, ServiceNow Tips, ServiceNow Tricks, ServiceNow Blog"

navbar-links:
  About Me: "aboutme"
  Resume: "https://simranjazz.com"

title-img: "/assets/images/NowGlideLogoInverse.png"

sidebar:
  featured: true
  recent_posts: true

defaults:
  favicon: /NowGlide/favicon.ico
  head-extra: <link rel='shortcut icon' type='image/x-icon' href='/NowGlide/favicon.ico?'>
  favicon: /favicon.ico
  head-extra: <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico?'>

favicon: /NowGlide/favicon.ico
head-extra: <link rel='shortcut icon' type='image/x-icon' href='/NowGlide/favicon.ico?'>

favicon: /favicon.ico
head-extra: <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico?'>