remote_theme: mmistakes/minimal-mistakes

title: NowGlide
description: Learn ServiceNow tips, tricks, and architecture!
url: "https://simranjazz.github.io"  # No trailing slash
baseurl: "/NowGlide"  # This is IMPORTANT for Project Page! (case-sensitive!)

# Build settings
markdown: kramdown