remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: NowGlide
description: Learn ServiceNow tips, tricks, and architecture!
url: "https://simranjazz.github.io"
baseurl: "/NowGlide"

# Build settings
markdown: kramdown
