remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide ServiceNow-verse
description: Glide Through ServiceNow-verse
url: "https://www.nowglide.com"
baseurl: ""
email: "simranjazz@gmail.com"
author: "Gursimran Singh Saini"
timezone: "Asia/Kolkata"

# Build settings
markdown: kramdown

site-css: assets/css/style.css

avatar: "/assets/images/gs.png"

social-network-links:
  email: "simranjazz@gmail.com"
  linkedin: "simranjazz"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: true
  reddit: true

url-pretty: "NowGlide.com"

post_search: true

title-on-all-pages: true

keywords: "ServiceNow, Service-Now, GlideFast, GlideSoft, ServiceNow Tips, ServiceNow Tricks, ServiceNow Blog, NowGlide"

navbar-links:
  About Me: "aboutme"
  Resume: "https://simranjazz.com"
  Tags: "/tags"

title-img: "/assets/images/NowGlideLogoInverse.png"

feed_show_tags: true

plugins:
  - jekyll-sitemap
  - jekyll-toc