remote_theme: daattali/beautiful-jekyll@6.0.1

title: NowGlide
description: Learn ServiceNow tips, tricks, and architecture!
url: "https://simranjazz.github.io"
baseurl: "/NowGlide"

# Build settings
markdown: kramdown

site-css:
  enable: true

site-css: assets/css/style.css